version: "3"

services:
      
  portainer:
    image: portainer/portainer:1.24.1
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dashboard/portainer/data:/data
    ports:
      - 9000:9000

  grafana:
    image: grafana/grafana:7.1.3
    container_name: grafana
    restart: always
    external_links:
      - prometheus
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel, grafana-simple-json-datasource
    networks: 
      - kong-net
    ports:
      - 3000:3000

networks:
  kong-net:
    driver: bridge